<h1>Registro de psicologos</h1>
</br>
<form id="formPsicologos">
<div class="row">
   <div class="col-md-3"></div>
   <div class="col-md-6">
       <label>Cedula: </label>
       <input type="text" name="cedula" class="form-control">
   </div>
</div>
    </br>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <label>Nombres: </label>
        <input type="text" name="nombre" class="form-control">
    </div>
</div>
    </br>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3">
        <label>Apellido Paterno: </label>
        <input type="text" name="apePaterno" class="form-control">
    </div>
    <div class="col-md-3">
        <label>Apellido Materno: </label>
        <input type="text" name="apeMaterno" class="form-control">
    </div>
</div>
    </br>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3">
        <label>Especialidad </label>
        <input type="text" name="especialidad" class="form-control">

    </div>
    <div class="col-md-3">
        <label>Numero de telefono: </label>
        <input type="text" name="phone" class="form-control">
    </div>
</div>
</br>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <label>Subir imagen de cedula: </label>
        <div id="some-dropzone" class="dropzone">
            <div class="dz-default dz-message">
                <h2 style="position: relative; top: -30px">
                    <i class="fa fa-cloud-upload" style="font-size: 88px;"></i><br>
                    Arrastra una imagen <br><i style="font-size: 14px;">o haz click para seleccionar manualmente</i>
                    <input type="hidden" value="" name="image-2" id="image-2">
                </h2>
            </div>
        </div>
    </div>
</div>
</br>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <button type="submit" class="boton_personalizado" >Registrarse</button>
        </div>
    </div>
</br>
</form>