

<div class="row">
    <div class="col-md-12">
        <section class="slide-wrapper">
            <div class="container">
                <div id="myCarousel" class="carousel slide">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item item1 active">
                            <div class="fill" style=" background-color:rgb(224,222,166);">
                                <div class="inner-content">
                                    <div class="carousel-img">
                                        <img src="<?=$this->url->get('front/img/pic4.jpg')?>" alt="sofa" class="img img-responsive" />
                                    </div>
                                    <div class="carousel-desc">
                                        <h2>Atencion Especializada</h2>
                                        <p></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item item2">
                            <div class="fill" style="background-color:rgb(38,110,183);">
                                <div class="inner-content">
                                    <div class="carousel-img">
                                        <img src="<?=$this->url->get('front/img/pic3.jpg')?>" alt="white-sofa" class="img img-responsive" />
                                    </div>
                                    <div class="carousel-desc">
                                        <h2>Nos preocupamos por usted</h2>
                                        <p></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item item2">
                            <div class="fill" style="background-color:rgb(28,163,157);">
                                <div class="inner-content">
                                    <div class="carousel-img">
                                        <img src="<?=$this->url->get('front/img/pic1.jpg')?>" alt="white-sofa" class="img img-responsive" />
                                    </div>
                                    <div class="carousel-desc">
                                        <h2>Los Mejores Especialistas</h2>
                                        <p></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h1 class="n60">Bienvenido a <span class="blue">Luz de amor</span></h1>
    </div>
    <div class="col-md-8">
        <aside>
            <h1>Quienes Somos</h1>
            <h3>
                Somos una empresa, que procura el trato amable a los pacientes, basados en los valores que forman parte de nuestra cultura organizacional, asi mismo somos una empresa con amplia conciencia social con el medio hambiente, todo esto nos hace una empresa eficiente que se distigue por el compromiso con la sociedad civíl y médica con la finalidad de contribuir y lograr el mejor diagnóstico y tratamiento a las personas que lo requieren, esto genera un esfuerzo en conjunto para preservar una sociedad saludable.
            </h3>
        </aside>
        <aside>
            <h1>Misión</h1>
            <h3>Grupo profesional dedicado a lograr la exelencia clínica - médica orientado a brindar servicios de innovacion en el cuidado de la salud con sensibilidad humana</h3>
        </aside>
        <aside>
            <h1>Visión</h1>
            <h3>Nuestra visión es ser la primera y mejor opción cuando pienses en las soluciones para el bienestar de tu familia</h3>
        </aside>
    </div>
</div>
<!-- <div class="row">
    <div class="col-md-12">
        <img src="img/Page1.png" alt="">
    </div>

</div> -->
</div>


<div class="row">
    <div class="col-md-6">
        <h3 style="font-size: 40px ;">Comentarios: <?=$numerosComentarios?></h3>
    </div>
</div>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">

        <div class="comentarios" >
            <?php foreach ($comentarios as $cnv):?>
             <div id="<?=$cnv->getCid()?>" class="comentary">
                 <h4 class="by-author"><?=$cnv->getNombre()?>
                 </h4>
             </div>
             <div class="comment-content">
                <p><?=$cnv->getComentario()?></p>
             </div>
             <?php endforeach; ?>
        </div>

    </div>
    </br>
</div>

<form id="formComent">
<div class="row">
    <h3>Dejenos su comentario</h3>
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <label>Nombre:</label>
        <input type="text" name="nombre" class="form-control">
    </div>
</div>
</br>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-2">
        <label>Comentario </label>
        <textarea name="comentario" style="width: 650px; height: 200px;"></textarea>
    </div>
</div>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <button type="submit" class="btn btn-lg btn-success">Comentar</button>
    </div>
</div>
</br>
</form>