<div class="row">
    <div class="col-md-12">
        <section class="slide-wrapper">
            <div class="container">

                <div class="row">
                    <div class="col-md-4">
                        <h1 class="n60">Conoce a <span class="blue">Dr</span><span>Patricio</span></h1>
                    </div>
                    <div class="col-md-8">
                        <aside>
                            <div align="center">
                                <img src="<?=$this->url->get('front/img/pic.jpg')?>" width="150px" heigth="100px" />
                            </div>
                        </aside>
                        <aside>
                            <h1>Empezemoos</h1>
                            <h3> Dr. Patricio Enrique Graue Wiechers</h3>
                            <h3>Médico Especialista Gastroenterologo en Academia Nacional de Medicina </h3>
                            <h3>Subsecretario de Integración y Desarrollo del Sector Salud.</h3>
                            <h3>Coordinador del Seminario Internacional sobre Políticas de Formación de Médicos Especialistas</h3>
                            <h3>Cedula Profesional: 4466809</h3>

                        </aside>
                        <aside>
                            <h1>Educacion Pregrado</h1>
                            <h3>•	Licenciatura en : Medico Cirujano </h3>
                            <h3>•	Internado de Pregrado: Hospital Sociedad Beneficencia Española de Puebla</h3
                        </aside>
                        <aside>
                            <h1>Educacion Postgrado</h1>
                            <h3>•	Especialista: Cirugía General, Hospital Central Sur de  Alta Especialidad PEMEX.
                                Avalado por la Universidad Autónoma de México
                            </h3>
                            <h3>•	Curso de Alta Especialidad en Medicina: Cirugía Endoscópica Gastrointestinal, Hospital Central Sur de  Alta Especialidad PEMEX.</h3>
                            <h3>•	Certificado por el Consejo Mexicano de Cirugía General el día 13 de Junio 2010.</h3>
                            <h3></h3>
                        </aside>
                        <aside>
                            <h1>Cursos impartidos</h1>
                            <h3>•	Curso “Ecos Endoscópicos”. Asociación Mexicana de Endoscopia Gatsrointestinal.  3 y 4 Julio 2010. México D.F. </h3>
                            <h3>•	Curso de Inducción a la Residencia en Endoscopia Digestiva. 19 y 20 de Febrero 2010. México D.F.</h3>
                            <h3>•	Curso de Cirugía de mínima invasión aplicada a las enfermedades de colon y recto, 20 y 21 de enero 2010: Asociación Mexicana de Cirugía General. México DF.</h3>
                            <h3>•	Curso de Cirugía de mínima invasión aplicada a las enfermedades de colon y recto, 20 y 21 de enero 2010: Asociación Mexicana de Cirugía General. México DF.</h3>
                        </aside>
                    </div>
                </div>
                <!-- <div class="row">
                    <div class="col-md-12">
                        <img src="img/Page1.png" alt="">
                    </div>

                </div> -->
            </div>