<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <link rel="stylesheet" href="<?=$this->url->get('front/css/bootstrap.min.css')?>">
      <link rel="stylesheet" href="<?=$this->url->get('front/css/ind.css')?>">
      <link rel="stylesheet" href="<?=$this->url->get('front/css/fileinput.min.css')?>">
      <link href="<?=$this->url->get('front/css/sweet-alert.css')?>" rel="stylesheet" type="text/css" >
      <link rel="stylesheet" href="<?=$this->url->get('front/css/myStyle.css')?>">
      <link rel="stylesheet" href="<?=$this->url->get('front/css/animate.min.css')?>">
      <link rel="stylesheet" href="<?=$this->url->get('bower_components/dropzone/dist/dropzone.css')?>">
      <link rel="stylesheet" href="<?=$this->url->get('front/css/font-awesome.min.css')?>">
      <link rel="stylesheet" href="<?=$this->url->get('front/css/formValidation.min.css')?>">
      <link href="<?=$this->url->get('dash/css/sweetalert.css')?>" rel="stylesheet" type="text/css" >
    <title>Luz de amor</title>
  </head>
  <header class="container-fluid bluebackground">
      <div class="row">
          <div class="col-md-2 hidden-xs hidden-sm">
              <a href="facebook.com">
                  <h4 class="white">
                      <img src="<?=$this->url->get('front/img/fb.png')?>" style="width:20%"alt="facebook"> Facebook
                  </h4>
              </a>
          </div>
          <div class="col-md-2 hidden-xs hidden-sm">
              <a href="twitter.com">
                  <h4 class="white">
                      <img src="<?=$this->url->get('front/img/tw.png')?>" style="width:20%"alt="twitter"> Twitter
                  </h4>
              </a>
          </div>
          <div class="col-md-4 hidden-xs hidden-sm">
              <p></p>
              <h4 class="white">

              </h4>
          </div>
      </div>
  </header>
  <body>
  <div class="container-fluid">
      <div class="row well">
          <div class="col-md-3">
            <a href="/">
              <img  src="<?=$this->url->get('front/img/LUZ_BAJA.png')?>" style="width: 200px;height: 200px;position: relative;left:50px">
            </a>
          </div>
          <div class="col-md-3">
              <a href="/acerca-de">
                  <h1 style="cursor:help;" data-toggle="tooltip" title="Click aqui para saber más">¿Que es luz de amor?</h1>
              </a>
          </div>
          <div class="col-md-2">
              <a href="/psicologos-registro">
                 <h3>Registrate como psicologo</h3>
              </a>
          </div>
          <div class="col-md-3">
              <h1>¿Fuiste afectado por los sismo?</h1>
              <h5 class="grey">Te asignamos un psicologo aquí</h5>
          </div>
          <div class="col-md-1"></div>
      </div>
      <div class="container" style="text-align: center;">
      <?= $this->getContent() ?>
      </div>
      <footer style="text-align: center;">
         <span> &copy; 2017</span>
      </footer>
      <script src="<?=$this->url->get('front/js/jquery.min.js')?>"></script>
      <script src="<?=$this->url->get('front/js/bootstrap.min.js')?>"></script>
      <script src="<?=$this->url->get('bower_components/dropzone/dist/min/dropzone.min.js')?>"></script>
      <script src="<?=$this->url->get('front/js/moment.min.js')?>"></script>
      <script src="<?=$this->url->get('front/js/uploadimage.js')?>"></script>
      <script src="<?=$this->url->get('front/js/carouselanimate.js')?>"></script>
      <script src="<?=$this->url->get('front/js/formValidation.min.js')?>"></script>
      <script src="<?=$this->url->get('front/js/bootstrapV.min.js')?>"></script>
      <script src="<?= $this->url->get('front/js/sweetalert.min.js')?>"></script>
      <script src="<?=$this->url->get('front/js/action.js')?>"></script>


  </body>
</html>
